spring.application.name=ProyectoMarcos

#spring.datasource.url=jdbc:postgresql://ep-little-violet-aqw9g8ur-pooler.c-8.us-east-1.aws.neon.tech:5432/Clinica_JosePardo
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_58XvIeNGasUj

#spring.datasource.url=jdbc:postgresql://localhost:5432/Clinica_JosePardo
#spring.datasource.username=postgres
#spring.datasource.password=rodrigo20041998

#spring.datasource.url=jdbc:postgresql://dpg-d850aprbc2fs73ckcokg-a.oregon-postgres.render.com:5432/clinica_josepardo 
#spring.datasource.username=aaron
#spring.datasource.password=cUos9ay4XpRxlDlczKFpWJCBybBlO6Ja

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
server.servlet.context-path=/

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**



#postgresql://aaron:cUos9ay4XpRxlDlczKFpWJCBybBlO6Ja@dpg-d850aprbc2fs73ckcokg-a.oregon-postgres.render.com/clinica_josepardo
