spring.application.name=ProyectoMarcos

# =============================================
# CONFIGURACION POSTGRESQL
# Cambia estos valores segun tu base de datos
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/Clinica_JosePardo
spring.datasource.username=postgres
spring.datasource.password="CorreoDelPostgres"
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080

# Contexto base (puedes cambiar si quieres otro puerto o contexto)
server.servlet.context-path=/

# Archivos estaticos
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
