spring.application.name=ProyectoMarcos

spring.datasource.url=jdbc:postgresql://localhost:5432/Clinica_JosePardo
spring.datasource.username=postgres
spring.datasource.password=rodrigo20041998
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
server.servlet.context-path=/

spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**